import luigi
from save_log import stop_watch
import time


class Pipeline:

    @stop_watch('Pipeline.run()')
    def run(self):
        luigi.run(['tasks.Task2', '--workers', '1', '--local-scheduler'])


class Task1(luigi.Task):
    task_namespace = 'tasks'

    @stop_watch("Task1")
    def run(self):
        with self.output().open("w") as target:
            target.write(f"This file was generated by Task1 at {time.asctime()}.")

    def output(self):
        return luigi.LocalTarget("luigi_task1.txt")


class Task2(luigi.Task):
    task_namespace = 'tasks'

    def requires(self):
        return Task1()

    def run(self):
        with self.input().open("r") as intermediate, self.output().open("w") as target:
            task1_text = intermediate.read()
            target.write(f"{task1_text}\n")
            target.write(f"This file was generated by Task2 at {time.asctime()}.")

    def output(self):
        return luigi.LocalTarget("luigi_task2.txt")


if __name__ == '__main__':
    luigi.run(['tasks.Task2', '--workers', '1', '--local-scheduler'])
